### ISSUE TITLE
Output should be sorted

### ISSUE THREAD

**Issue by trquinn** [paratreet/paratreet#16]
The test output isn't useful since the particles are not in their original order.
Perhaps a Writer group needs to be implemented that can be used to hold the particles sorted by their "order" attribute.

**Comment by minitu** [comment]
Yes I just found this out yesterday, we need to implement `TreePiece::reOrder` from ChaNGa's `InOutput.cpp`.
@AjayMT will start working on this.

**Comment by minitu** [comment]
Fixed by #17, closing.
