### ISSUE TITLE
Make sendLeaves smarter

### ISSUE THREAD

**Issue by mojoe12** [paratreet/paratreet#80]
1. we dont want to do our own partition_lookup in CacheManager. We instead want to use ckLocal but an implementation that works for SMP.
2. we dont want to send the very large flat_subtree to multiple partitions on the same process. I would like to ask the charm RTS to help us with this. As in, chare.getNode(). Since partitions dont move in between iterations, this would be in-iteration static but not between-iteration static. This is problematic, but the RTS has to deal with it, so it should be able to just expose that information to us.

**Comment by Wingpad** [comment]
Regarding (1), there does not appear to be a node-wide store of which array elements are on the node. This means that, for exact information, one would have to query all of the PE's within the node to see if an array element is on the node, which could be rather inefficient on many-core systems. Instead, we could use the last known location from the location manager, but this can be inaccurate when there is a lot of migration happening. I am still researching the location manager to see if there is a more exact way to query it, and will ask some of my collaborators within the group if they know anything along these lines. In the meantime, here is a solution using the non-exact/approximate function lastKnown:

    template<typename T>
    void* getLocalElement(T& thisProxy, int idx_) {
        auto idx = thisProxy[idx_].ckGetIndex();
        int lastPe = thisProxy.ckLocalBranch()->lastKnown(idx);
        if (CkMyNode() == CkNodeOf(lastPe)) {
            return thisProxy.ckLocalBranchOther(lastPe)->lookup(idx);
        } else {
            return nullptr;
        }
    }

**Comment by mojoe12** [comment]
This is great. Was wondering, with this less exact solution, can we leverage the fact there are iterations and they don't move between iterations? When does last known() get updated?

**Comment by Wingpad** [comment]
Unsure, will look into this and update.

> This is great. Was wondering, with this less exact solution, can we leverage the fact there are iterations and they don't move between iterations? When does last known() get updated?

I will look into this and get back to you, I am unsure whether it's updated on an on-demand basis or in a more systematic way. That being said, since migrations do not occur during an iteration, once its updated it will be correct and can be used throughout the iteration.

**Comment by Wingpad** [comment]
A PE's `lastKnown` location for an element is updated in two ways. If it is the home PE of the element, it is updated whenever the element migrates. If not, it is updated on an on-demand basis; whenever a message takes too many hops to reach its destination, the receiver sends an updated location to the sender.  This means that, if a PE never tries to message an element [it is not the home PE of], its lastKnown will never be updated.

As for node-aware location tables, Sanjay made me aware of the Array Listener interface. It "listens" for updates to an array on a given PE, which includes whenever an element migrates onto that PE. We could use this to roll our own node-aware location table if we so choose, i.e. using a `nodegroup` with a map that all the array listener updates of the local PEs are funneled to. It's not well documented, but I think I understand the gist of it.

**Comment by Wingpad** [comment]
In my exploration of CkLocalBranchOther, I have found that it can be unreliable. Depending on the configuration, it may not successfully return a pointer to the object on the other PE. For SMP run where there is only one process per node or one worker thread per process, it seems OK; however, when there are multiple worker threads per process and multiple processes, it seems to be prone to consistent failure (on my machine).

Here is a test program and a demonstration of the problem: https://gist.github.com/Wingpad/8f0f1d1e62bedee7b23b2e2c5f1d83d7

**Comment by Wingpad** [comment]
Alright, I figured out how `CkLocalBranchOther` works -- you have to pass it `CkRankOf` and not the PE number!

```
template<typename T>
void* ckNodeAwareLocal(T& thisProxy, int idx_) {
  auto idx = thisProxy[idx_].ckGetIndex();
  int lastPe = thisProxy.ckLocalBranch()->lastKnown(idx);
  if (CkMyNode() == CkNodeOf(lastPe)) {
    return thisProxy.ckLocalBranchOther(CkRankOf(lastPe))->lookup(idx);
  } else {
    return nullptr;
  }
}
```

I have a working demo now at: https://gist.github.com/Wingpad/3b0f2bdc26b4ac4eb83a37598fbcf935

**Comment by mojoe12** [comment]
Great! Can we get this into a PR and test it with load balancing on multiple logical nodes?

**Comment by Wingpad** [comment]
Made a PR, and could try to make a few comparative runs. Are there any configurations you are interested in seeing the results for, in particular? Like, which combination of dataset/decomposition/load balancer should I use?

**Comment by mojoe12** [comment]
This was fully investigated by Justin and is no longer a pending issue.
